<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Authors>Krivodeling</Authors>
    <Copyright>Copyright © 2026 Krivodel</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>Pica.PackageIcon.png</PackageIcon>
    <PicaRepositoryUrl>https://github.com/Krivodel/Pica</PicaRepositoryUrl>
    <PackageProjectUrl>$(PicaRepositoryUrl)</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>pica;image-viewer;image;view;viewer;avalonia</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>$(PicaRepositoryUrl).git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)README.md"
          Pack="true"
          PackagePath="\"
          Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)assets\Pica.PackageIcon.png"
          Pack="true"
          PackagePath="\"
          Visible="false" />
  </ItemGroup>
</Project>
