<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Pica.Build.props" />

  <PropertyGroup>
    <AssemblyTitle>$(PicaApplicationName)</AssemblyTitle>
    <Version>$(PicaVersion)</Version>
    <PackageVersion>$(PicaPackageVersion)</PackageVersion>
    <PackageId>Pica.Protocol</PackageId>
    <Description>Communication contracts between Pica and calling applications.</Description>
  </PropertyGroup>
</Project>
