<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Pica.Viewer\Pica.Viewer.csproj" />
    <ProjectReference Include="..\Pica.Tests.Common\Pica.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\Pica.Viewer\Assets\AppIcon.ico"
          Link="AppIcon.ico"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
