namespace Pica.Viewer.Tests.Services;

internal static class HeicImageTestData
{
    internal const int Width = 100;
    internal const int Height = 100;

    private const string ContentBase64 =
        """
        AAAAJGZ0eXBoZWljAAAAAG1pZjFNaVBybWlhZk1pSEJoZWljAAABwm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAHBpY3QAAAAAAAAA
        AAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAADnBpdG0AAAAAAAEAAAA4aWluZgAAAAAAAgAAABVp
        bmZlAgAAAAABAABodmMxAAAAABVpbmZlAgAAAQACAABFeGlmAAAAABppcmVmAAAAAAAAAA5jZHNjAAIAAQABAAAA5WlwcnAAAADE
        aXBjbwAAABNjb2xybmNseAACAAIABoAAAAAMY2xsaQDLAEAAAAAUaXNwZQAAAAAAAABkAAAAZAAAAAlpcm90AAAAABBwaXhpAAAA
        AAMICAgAAABwaHZjQwEDcAAAALAAAAAAAB7wAPz9+PgAAAsDoAABABdAAQwB//8DcAAAAwCwAAADAAADAB5wJKEAAQAiQgEBA3AA
        AAMAsAAAAwAAAwAeoBQgccPz4h7kWVTcCAgYAqIAAQAJRAHAYXLIRFNkAAAAGWlwbWEAAAAAAAAAAQABBoECA4QFhgAAACxpbG9j
        AAAAAEQAAAIAAQAAAAEAAAJCAAADDgACAAAAAQAAAfYAAABMAAAAAW1kYXQAAAAAAAADagAAAAZFeGlmAABNTQAqAAAACAADARoA
        BQAAAAEAAAAyARsABQAAAAEAAAA6ASgAAwAAAAEAAgAAAAAAAAAAAEgAAAABAAAASAAAAAEAAAMKKAGvkFA5aAEQRoF8/+wP6/6p
        f//d84+xb9nmsaJflf/3R63+A30iekZpp9PDhKnrYJO/09PgFyZeSIX59QPQrEfsCYyLCIEHQVvVwLOdkJbUlVzpeY96iiLgIbN9
        qOaotX1N4l/qnMcDhLYLmU7mt8OTYGDSZZdWAaDD9xS9zdXS8I3TdvVMNyrgV3/f1pLuV38bJjG9baAEyjBdUYOXlwRF0xMwXtNy
        paKba0oD6phayt8d43gnn42mqILF7841CaerUm3Z3SzGfOTbKwxLBvfcDkp4B9uVnTZx9WD5j5a+oIxW4GiSZ/8360Npao8EwK2O
        H+wl/lzMhCl4F2A0h+ivMI3YolAwC4gQaRA1BP4W8eL/kJye4RxNTVoWmlpT15ZU6nPpOoAXiUPIdv5HteTZh4Y60uaSh7OUY8bB
        +HU2r/iSK6YpiBtfgA2K5v6S+WqSRZ3WskuQAicCLTk69ZpgrOTkFA1V/Wk65R36+T6iipvaIPPKkmUnB+Pld3e//UG3/zFp7TeK
        CgFWMje0HFFrYolmdEooihv5BA2J50rS0HLXs6npCh+/JFaQ3LVHZ4I9Stb7iUrwfu+wM2AQacTbnPej5cQf3wjCis056nLv83Nr
        c6qZxVavmiRRLOnioO/Z0Js7/Z/j0p//9zeHpwA0mhLGobvV4l/Itzk6SpenJpdCrvSyWzy9czH3kf8iTq0675oRFvCgXtzDiImT
        c1I8JSJfo8jON/ng69V7X+AFCpbe6nE2wg/Au03SSxagAuLQyg+MeGC32TM2/7fcOI47uqa30GyUHmEuEPfiFDBLxJekGDY3x+uB
        ekcZcVHwKC1UfMnMJT3X7hoyz2MfAAkhgf6syzmSF0kQEvMLZng30BGNQXg0jvqLKstov9rkPDHZ/ndrHWhMq93IPEUodvnSX9H4
        e/wtkn8YUiVA/2D+AKFNQxzwCCIFZvcFWJV9FBN1TYMU4vPO9OI13o9u4mgtyQOwF/tgr+9FFv191a2W88fMY3ugVMWyRiMr1t9g
        SN8HXWAADPnJYA==
        """;

    internal static void Create(string path)
    {
        byte[] content = Convert.FromBase64String(ContentBase64);
        File.WriteAllBytes(path, content);
    }
}
