namespace Pica.Viewer.Tests.Services;

internal static class TiffImageTestData
{
    internal const int Width = 4;
    internal const int Height = 3;

    private const string ContentBase64 =
        """
        SUkqACAAAACAEZBLRkQKCQaCwOEweFQiHQ2IQyCQEAALAAABAwABAAAABAAAAAEBAwABAAAAAwAAAAIBAwAEAAAAqgAAAAMBAwAB
        AAAABQAAAAYBAwABAAAAAgAAABEBBAABAAAACAAAABUBAwABAAAABAAAABYBAwABAAAAAwAAABcBBAABAAAAFwAAABwBAwABAAAA
        AQAAAFIBAwABAAAAAgAAAN4AAAAIAAgACAAIAAAAAAAAAAAAAAAAAAAASUkqAB4AAACANwKDx/wKCQaCwOEweFQiHQ2FQEAACwAA
        AQMAAQAAAAIAAAABAQMAAQAAAAUAAAACAQMABAAAAGgBAAADAQMAAQAAAAUAAAAGAQMAAQAAAAIAAAARAQQAAQAAAMgAAAAVAQMA
        AQAAAAQAAAAWAQMAAQAAAAUAAAAXAQQAAQAAABUAAAAcAQMAAQAAAAEAAABSAQMAAQAAAAIAAAAAAAAACAAIAAgACAA=
        """;

    internal static void Create(string path)
    {
        byte[] content = Convert.FromBase64String(ContentBase64);
        File.WriteAllBytes(path, content);
    }
}
