<Project>
  <PropertyGroup>
    <PicaApplicationName>Pica</PicaApplicationName>
    <PicaVersion>1.1.2</PicaVersion>
    <PicaPackageVersion>1.1.2-preview.1</PicaPackageVersion>
    <PicaWindowsX64RuntimeIdentifier>win-x64</PicaWindowsX64RuntimeIdentifier>
    <PicaWindowsArm64RuntimeIdentifier>win-arm64</PicaWindowsArm64RuntimeIdentifier>
    <PicaLinuxX64RuntimeIdentifier>linux-x64</PicaLinuxX64RuntimeIdentifier>
    <PicaLinuxArm64RuntimeIdentifier>linux-arm64</PicaLinuxArm64RuntimeIdentifier>
    <PicaMacX64RuntimeIdentifier>osx-x64</PicaMacX64RuntimeIdentifier>
    <PicaMacArm64RuntimeIdentifier>osx-arm64</PicaMacArm64RuntimeIdentifier>
    <PicaRuntimeIdentifiers>$(PicaWindowsX64RuntimeIdentifier);$(PicaWindowsArm64RuntimeIdentifier);$(PicaLinuxX64RuntimeIdentifier);$(PicaLinuxArm64RuntimeIdentifier);$(PicaMacX64RuntimeIdentifier);$(PicaMacArm64RuntimeIdentifier)</PicaRuntimeIdentifiers>
  </PropertyGroup>
</Project>
